spring.application.name=secure_config_server
# Server port (default is 8888)
server.port=8888

# Git repository configuration
spring.cloud.config.server.git.uri=https://github.com/mubashir142/secure_config_server.git
spring.cloud.config.server.git.clone-on-start=true

# Basic authentication credentials
spring.security.user.name=admin
spring.security.user.password=secret